#!/usr/bin/env bash
set -euo pipefail

# --- template configuration --------------------------------------------------
# bin_name must match the package name in Cargo.toml.
# -----------------------------------------------------------------------------
bin_name="greet"

block_begin="# >>> $bin_name completions >>>"
block_end="# <<< $bin_name completions <<<"

install_dir="$HOME/.local/bin"
termux_prefix=""
if [[ -n "${PREFIX:-}" &&
    ( -n "${TERMUX_VERSION:-}" ||
    "${PREFIX:-}" == */com.termux/files/usr ||
    ( -n "${ANDROID_ROOT:-}" && -n "${ANDROID_DATA:-}" ) ) ]]; then
    termux_prefix="${PREFIX:-}"
    install_dir="$termux_prefix/bin"
fi
home_zsh_completion="$HOME/.local/share/zsh/site-functions/_$bin_name"
home_bash_completion="$HOME/.local/share/bash-completion/completions/$bin_name"
home_fish_completion="$HOME/.config/fish/completions/$bin_name.fish"
zsh_completion="$home_zsh_completion"
bash_completion="$home_bash_completion"
fish_completion="$home_fish_completion"
if [[ -n "$termux_prefix" ]]; then
    zsh_completion="$termux_prefix/share/zsh/site-functions/_$bin_name"
    bash_completion="$termux_prefix/share/bash-completion/completions/$bin_name.bash"
    fish_completion="$termux_prefix/share/fish/vendor_completions.d/$bin_name.fish"
fi

is_generated_completion() {
    local path="$1"

    [[ -f "$path" ]] &&
        grep -Fq "@generated by usage-argv for \`$bin_name __complete_word__" "$path"
}

remove_installed_binary() {
    local path="$1"

    [[ -e "$path" || -L "$path" ]] || return 0
    rm -f -- "$path"
    printf 'Removed %s\n' "$path"
}

remove_generated_completion() {
    local path="$1"

    [[ -e "$path" || -L "$path" ]] || return 0
    if ! is_generated_completion "$path"; then
        printf 'Skipped unrelated completion file %s\n' "$path" >&2
        return
    fi

    rm -f -- "$path"
    printf 'Removed %s\n' "$path"
}

resolve_symlink() {
    local path="$1"
    local link_target
    local depth=0

    while [[ -L "$path" ]]; do
        link_target="$(readlink "$path")"
        if [[ "$link_target" == /* ]]; then
            path="$link_target"
        else
            path="$(dirname -- "$path")/$link_target"
        fi
        depth=$((depth + 1))
        if (( depth > 20 )); then
            return 1
        fi
    done

    printf '%s\n' "$path"
}

hard_link_count() {
    local path="$1"

    if [[ "$(uname -s)" == Darwin ]]; then
        stat -f '%l' "$path"
    else
        stat -c '%h' "$path"
    fi
}

file_mode() {
    local path="$1"

    if [[ "$(uname -s)" == Darwin ]]; then
        stat -f '%Lp' "$path"
    else
        stat -c '%a' "$path"
    fi
}

# Print the profile without its managed block, dropping the blank line the
# installer wrote in front of it.
strip_block() {
    awk -v begin="$block_begin" -v end="$block_end" '
        $0 == "" { held++; next }
        $0 == begin {
            for (index_ = 1; index_ < held; index_++) print ""
            held = 0
            inside = 1
            next
        }
        inside && $0 == end { inside = 0; next }
        inside { next }
        { while (held > 0) { print ""; held-- } print }
        END { while (held > 0) { print ""; held-- } }
    ' "$1"
}

clean_profile() {
    local config_file="$1"
    local profile_file filtered_file replacement_file link_count original_mode

    [[ -f "$config_file" ]] || return 0
    profile_file="$(resolve_symlink "$config_file")" || {
        printf 'Skipped unresolved profile symlink %s\n' "$config_file" >&2
        return 0
    }
    grep -Fqx -- "$block_begin" "$profile_file" || return 0

    link_count="$(hard_link_count "$profile_file")"
    if (( link_count > 1 )); then
        printf 'Skipped hard-linked profile %s\n' "$config_file" >&2
        return 0
    fi

    filtered_file="$(mktemp "${profile_file}.$bin_name-filtered.XXXXXX")"
    if ! strip_block "$profile_file" > "$filtered_file"; then
        rm -f -- "$filtered_file"
        return 1
    fi

    if cmp -s "$profile_file" "$filtered_file"; then
        rm -f -- "$filtered_file"
        return 0
    fi

    if ! replacement_file="$(mktemp "${profile_file}.$bin_name-replacement.XXXXXX")"; then
        rm -f -- "$filtered_file"
        return 1
    fi
    if ! original_mode="$(file_mode "$profile_file")" ||
        ! cp -p "$profile_file" "$replacement_file" ||
        ! chmod u+w "$replacement_file" ||
        ! cat "$filtered_file" > "$replacement_file" ||
        ! chmod "$original_mode" "$replacement_file" ||
        ! mv -f "$replacement_file" "$profile_file"; then
        rm -f -- "$filtered_file" "$replacement_file"
        return 1
    fi

    rm -f -- "$filtered_file"
    printf 'Removed %s entries from %s\n' "$bin_name" "$config_file"
}

remove_installed_binary "$install_dir/$bin_name"
if [[ "$install_dir" != "$HOME/.local/bin" ]]; then
    remove_installed_binary "$HOME/.local/bin/$bin_name"
fi
remove_generated_completion "$zsh_completion"
remove_generated_completion "$bash_completion"
remove_generated_completion "$fish_completion"
if [[ -n "$termux_prefix" ]]; then
    remove_generated_completion "$home_zsh_completion"
    remove_generated_completion "$home_bash_completion"
    remove_generated_completion "$home_fish_completion"
fi

zsh_config_dir="${ZDOTDIR:-$HOME}"
[[ "$zsh_config_dir" == /* ]] || zsh_config_dir="$HOME"

for config_file in \
    "$HOME/.zshrc" \
    "$zsh_config_dir/.zshrc" \
    "$HOME/.bashrc" \
    "$HOME/.bash_profile" \
    "$HOME/.bash_login" \
    "$HOME/.profile" \
    "$HOME/.config/fish/config.fish"; do
    clean_profile "$config_file"
done

printf '%s has been uninstalled.\n' "$bin_name"
