mod cli;

use cli::Greet;
use usage::Run;

fn main() {
    // `parse()` handles help, version, errors, and completion requests.
    // `run()` is the match generated by `#[usage(run)]`.
    Greet::parse().command.run()
}
